global:
  enabled_azure_upbound: true

deploymentRuntimeConfig:
  enabled: false
  metadata:
    name: "default"
    role_arn: ""
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
  spec:
    deploymentTemplate:
      metadata:
        labels:
          azure.workload.identity/use: "true"
      spec:
        replicas: 1
        template:
          securityContext:
            fsGroup: 2000
          containers:
          - name: package-runtime
            args:
            - --debug
    serviceAccountTemplate:
      metadata: 
        labels:
            azure.workload.identity/use: "true"  

provider:
  enabled: true
  metadata:
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
  package:
    registry: xpkg.upbound.io/upbound
    version: v0.42.0

providerConfig:
  enabled: true
  metadata:
    name: default
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
  spec:
    credentials:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: azure-secret
        key: creds
    
providers:
- network
- compute
- storage
- authorization
- containerservice
- containerregistry
- keyvault
- operationalinsights
- insights
- managedidentity
- resources
