apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fleet-hub-secret-store
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
  - matrix:
      generators:
        - matrix:
            generators:
              - clusters:
                  selector:
                    matchLabels:
                      fleet_member: hub-cluster
                  values:
                    addonChart: fleet-secret
                    fleet_memeber: hub-cluster           
                    addonChartPath: "charts/fleet-secret"
              - git:
                  repoURL: '{{ .metadata.annotations.fleet_repo_url }}'
                  revision: '{{ .metadata.annotations.fleet_repo_revision }}'
                  files:
                    - path: "{{ .metadata.annotations.fleet_repo_basepath }}/bootstrap/versions/fleetSecrets.yaml"
        - list:
            elementsYaml: "{{ .releases | toJson }}"
  ###################################################
  #base template (everything common)
  ###################################################
  template:
    metadata:
      name: 'fleet-hub-secret-store-{{.nameNormalized}}'
    spec:
      project: default
      destination:
        namespace: argocd
        name: '{{ .name }}'
      # syncPolicy is identical for both variants
      syncPolicy:
        automated:
          selfHeal: false
          allowEmpty: true
          prune: false
        retry:
          limit: 100
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  ###################################################
  # conditional sources
  ###################################################
  templatePatch: |
    spec:
      sources:
        - repoURL: '{{.metadata.annotations.addons_repo_url}}'
          targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
          ref: addonsValues
        - repoURL: '{{.metadata.annotations.resources_repo_url}}'
          targetRevision: '{{.metadata.annotations.resources_repo_revision}}'
          ref: resourcesValues
       {{- if  eq .use_helm_repo_path "false" }}
        - repoURL: '{{ .chartRepo }}'
          chart: '{{ default .values.addonChart .ecrChartName  }}'
          targetRevision: '{{.version}}'
      {{- else }}
        - repoURL: '{{ .metadata.annotations.fleet_repo_url }}'
          path: '{{ .values.addonChartPath }}'
          targetRevision: '{{ .metadata.annotations.fleet_repo_revision }}'
      {{- end }}
          helm:
            releaseName: '{{.nameNormalized}}'
            ignoreMissingValueFiles: true
            valuesObject:
              secretStore:
                enabled: true
                name: "fleet-eks-secret-store"
                kind: "SecretStore"
                region: '{{.metadata.annotations.aws_region}}'
              externalSecret:
                enabled: true
                server: self
                creationPolicy: Merge
                targetName: '{{.name}}'
                clusterName: '{{.name}}'
                secretManagerSecretName: 'hub/{{.name}}'
                secretStoreRefName: fleet-eks-secret-store
                secretStoreRefKind: SecretStore                
            ignoreMissingValueFiles: true
            valueFiles:
              - $addonsValues/{{.metadata.annotations.addons_repo_basepath}}/defaults/fleet/{{.values.addonChart}}/values.yaml
              - $addonsValues/{{.metadata.annotations.addons_repo_basepath}}/{{.metadata.labels.tenant}}/fleet/{{.values.addonChart}}/values.yaml
              - $addonsValues/{{.metadata.annotations.addons_repo_basepath}}/{{.metadata.labels.tenant}}/clusters/{{.name}}/fleet/{{.values.addonChart}}/values.yaml
              - $resourcesValues/{{.metadata.annotations.resources_repo_basepath}}/defaults/fleet/{{.values.addonChart}}/values.yaml
              - $resourcesValues/{{.metadata.annotations.resources_repo_basepath}}/{{.metadata.labels.tenant}}/fleet/{{.values.addonChart}}/values.yaml
              - $resourcesValues/{{.metadata.annotations.resources_repo_basepath}}/{{.metadata.labels.tenant}}/clusters/{{.name}}/fleet/{{.values.addonChart}}/values.yaml