{{- if (eq (toString .Values.externalSecret.enabled) "true")}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fleet-secret.fullname" . }}
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRefKind }}
    name: {{ .Values.externalSecret.secretStoreRefName }}
  refreshInterval: "1m"
  target:
    name: {{ .Values.externalSecret.targetName | default (include "fleet-secret.fullname" .) }}
    creationPolicy: {{ default "Owner" .Values.externalSecret.creationPolicy }}
    template:
      engineVersion: v2
      templateFrom:
      - target: Annotations
        literal: "{{`{{ .metadata }}`}}"
      {{- if .Values.externalSecret.annotations }}
      - target: Annotations
        literal: |-
          {{- .Values.externalSecret.annotations  | toYaml | nindent 10  }}
      {{- end }}
      {{- if .Values.externalSecret.labels }}
      - target: Labels
        literal: |-
          {{- .Values.externalSecret.labels  | toYaml | nindent 10  }}
      {{- end }}
      - target: Labels
        literal: "{{`{{ .addons }}`}}"
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: cluster"
      data:
        config: "{{`{{ .config }}`}}"
        name: {{ .Values.externalSecret.clusterName }}
        server: {{ if eq .Values.externalSecret.server "self" }}"https://kubernetes.default.svc"{{ else }}"{{`{{ .server }}`}}"{{ end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.secretManagerSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
