{{- if .Values.gitExternalSecrets.enabled }}
{{- $secretStoreRefName := .Values.gitExternalSecrets.secretStoreRefName -}}
{{- $secretStoreRefKind := .Values.gitExternalSecrets.secretStoreRefKind -}}
{{- $useHttp := .Values.gitExternalSecrets.useHttp -}}
{{- $useGitHubApp  := .Values.gitExternalSecrets.useGitHubApp | default false  -}}
{{- $usePrivateKey  := .Values.gitExternalSecrets.usePrivateKey | default false  -}}
{{- range $externalSecretName, $externalSecret := .Values.gitExternalSecrets.externalSecrets }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $externalSecretName }}
spec:
  secretStoreRef:
    kind: {{ $secretStoreRefKind }}
    name: {{ $secretStoreRefName }}
  refreshInterval: "1m"
  target:
    name: {{ $externalSecret.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Labels
        literal: "argocd.argoproj.io/secret-type: repository"
      data:
        type: "git"
        {{- if  $externalSecret.gitUrl }}       
        url: {{ $externalSecret.gitUrl }}
        {{- else }}
        url: "{{`{{ .url }}`}}"
        {{- end }}
        {{- if $useHttp }}
        username: "{{`{{ .username }}`}}"
        password: "{{`{{ .password }}`}}"
        {{- end }}
        {{- if $usePrivateKey }}
        insecureIgnoreHostKey: "true"
        sshPrivateKey: "{{`{{ .private_key }}`}}"
        {{- end }}
        {{- if $useGitHubApp }}
        githubAppID: "{{`{{ .github_app_id }}`}}"
        githubAppInstallationID: "{{`{{ .github_app_installation_id }}`}}"
        githubAppPrivateKey:  "{{`{{ .github_private_key }}`}}"
        {{- end }}
  dataFrom:
    - extract:
        key: {{ $externalSecret.secretManagerSecretName }}
        decodingStrategy: Auto
---
{{- end }}
{{- end }}
