{{- if and .Values.global.enabled_azure_upbound .Values.deploymentRuntimeConfig.enabled }}
{{- with .Values.deploymentRuntimeConfig }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .metadata.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    {{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

  {{- if .metadata.labels }}
  labels:
    {{- range $key, $value := .metadata.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  serviceAccountTemplate:
  {{- .spec.deploymentTemplate | toYaml | nindent 4 }}
  deploymentTemplate:
  {{- .spec.serviceAccountTemplate | toYaml | nindent 4 }}
{{- end }}
{{- end }}
